operaciones= function(x,y){
  print("suma")
  print(paste(sprintf("%i + %i = ",x,y),x+y))
  print("resta")
  print(paste(sprintf("%i - %i = ",x,y),x-y))
  print(paste(sprintf("%i - %i = ",y,x),y-x))
  print("Resultado de la multiplicacion")
  print(paste(sprintf("%i * %i = ",x,y),x*y))
  print("Cociente de la division entera")
  print(x%/%y)
  print("Resto de la Division Entera")
  print(paste(sprintf("%i dividido %i = ",x,y),x%%y))
  print(paste("Con resto",x%%y))
  print(paste(sprintf("%i dividido %i = ",y,x),y%%x))
  print(paste("Con Resto",y%%x))
  print("Resultado de la Potenciacion")
  print(paste(sprintf("%i pot %i=",x,y),x**y))
  print(x**y)
  print("Resultado de la radicacion")
  print(x**1/y)
}
operaciones(25,5)
