---
title: "apuntes_descriptiva"
author: "gonzalo"
date: "27/10/2020"
output: html_document
---

# Descargar e instalar paquetes

- Para descargar un paquete con el siguiente comando entre parentecis y comillas el       nombre del paquete 


install.packages("nombre_Paquete",dependencies = TRUE)


- Para cargar un paquete ya instalado

library(nombre_paquete)

# Operaciones Matematicas
- Suma  para sumar en `R` se utiliza el operador $+$ para que quede de la siguiente     manera $2+2=$ `r 2+2`.

- Resta para restar con `R` se utiliza el operador $-$ La operacion queda de la         siguiente manera $5-3=$ `r 5-3`.

- Producto para hallar el prducto en `R` se utiliza el operador $\cdot$ la operacion    quedaria $5\cdot3=$ `r 5*3`.

- Producto tambien  se puede utilizar $\times$ opera asi $5\times3=$ `r 5*3`.

- Division= en `R` funciona asi $5\div3=$ `r round(5/3,2)`. redondeando a dos           decimales

-  Potencia: funciona en `R`de la siguiente manera $5^{2}=$ `r 5^2`.

- Raiz n-ésima: funciona en `R` asi $\sqrt[3]{9}=$ `r 9^(1/3)`.

- Fracccion: Para representar una fraccio en `R` $\frac{1}{3}=$ `r 1/3`.

- Simbolo mas menos en `R` para escribir mas o menos 2 $\pm 2$

- Union se saca: $\cup$

- Union grande $\bigcup$

- Interseccion $\cap$

- Intersecion grande $\bigcap$

- or logico $\vee$

- or grande $\bigvee$

- and logico $\wedge$

- and grande $\bigwedge$

# Simbolos matematicos de Relaciones 

- igual $=$

- Aproximado $\approx$

- No igual $\ne$

- Mayor que $>$

- Menor que $<$

- Mayor igual que $\ge$

- Menor igual que $\le$

- sumatorio $\sum_{i=0}^{n}$

# Delimitadores

- Paréntecis $()$

- Corchetes $[]$

- llaves $\{\}$

- Diamante $\langle \rangle$

- Parte entera por defecto $\lfloor\rfloor$

- espacio en blaco hola\ gonzalo

# Letras Griegas

- alpha $\alpha$

- Beta $\beta$

- Gamma $\gamma \Gamma$

- Delta $\delta \Delta$

- Epsilon $\epsilon$

- Epsilon $\varepsilon$

- Zeta $\zeta$

- Pi $\pi$

- Pi $\Pi$

- Tau $\tau$

- Omega $\Omega$

# Acentos Matematicos

- Gorrito  $\hat{x}$

- Barra $\bar{x}$

- Un punto $\dot{x}$

- dos puntos $\ddot{x}$

- tres puntos $\dddot{x}$

- Tilde $\tilde{x}$

- Vector $\vec{x}$

Para trabajar una fracción al interior de un parrafo hay dos formas $\frac{a}{b}$ o se puede hacer al tamaño real del texto manejado $\dfrac{a}{b}$

Se puede especificar que los delimitadores en este caso los parentecis se ajuste al tamaño de la expresion : $(\dfrac{a}{b})$ y  $\left(\dfrac{a}{b}\right)$


# Matrices

Para realizar una matriz se procede de la siguiente manera  begin = empezar end =fin

Cuando no se le coloca nada realiza la matrix sin encerrarla 

$$\begin{matrix} a_{11} & a_{12} & a_{13} \\ b_{21} & b_{22} & b_{23}\\ c_{31} & c_{32} & c_{33} \end {matrix}$$
Cuando ante de la expresion matrix se le coloca una p la encierra en corchetes

$$\begin{pmatrix} a_{11} & a_{12} & a_{13} \\ b_{21} & b_{22} & b_{23}\\ c_{31} & c_{32} & c_{33} \end {pmatrix}$$
Cuando antes de la expresion matrix se le coloca una v la encierra en barras

$$\begin{vmatrix} a_{11} & a_{12} & a_13 \\ b_{21} & b_{22} & b_{23} \\ c_{31} & c_{32} & c_{33} \end {vmatrix}$$
Cuando antes de la expresion matrix se le coloca una b la encierra en un corchete

$$\begin{bmatrix} a_{11} & a_{12} & a_{13} \\ b_{21} & b_{22} & b_{23} \\ c_{31} & c_{32} & c_{33} \end {bmatrix}$$
Cuando antes de la expresion matrix se le coloca una B los encierra con llaves

$$\begin{Bmatrix} a_{11} & a_{12} & a_{13} \\ b_{21} & b_{22} & b_{23} \\ c_{31} & c_{32} & c_{33} \end{Bmatrix}$$
Cuando antes de la expresion matrix se le coloca la V los encierra en doble bara

$$\begin{Vmatrix} a_{11} & a_{12} & a_{13} \\ b_{21} & b_{22} & b_{23} \\ c_{31} & c_{32} & c_{33} \end {Vmatrix}$$

# Sistema de Ecuaciones 
Cuando se quiere colocar un parentecis al cerrar o al derecha

$$\left.\begin{array}{l} ax + by = c \\ ex-fy=g \end{array}\right\}$$ 



```{r}
2+2
```
